"""
Task and TaskType Models
"""
from sqlalchemy import Column, Integer, String, ForeignKey, Text, DateTime, Boolean, JSON
from sqlalchemy.sql import func
from app.db.database import Base

class TaskType(Base):
    """Root-Admin configurable task categories"""
    __tablename__ = "task_types"
    
    id = Column(Integer, primary_key=True, index=True)
    name = Column(String, unique=True, nullable=False)
    description = Column(Text)
    color = Column(String)  # Hex colour code
    sort_order = Column(Integer, default=0)  # For ordering in UI
    is_active = Column(Boolean, default=True)
    fatigue_score = Column(Integer, default=0)  # Fatigue score per minute (positive = straining, negative = restoring)
    # False keeps assignments blocking while excluding their duration from work limits.
    counts_towards_work_time = Column(Boolean, default=True, nullable=False)
    
    created_at = Column(DateTime(timezone=True), server_default=func.now())
    updated_at = Column(DateTime(timezone=True), onupdate=func.now())

class Task(Base):
    """
    Tasks created from templates with four-field separation:
    
    1. constraints (JSON): Optimisation INPUTS
       - Required capabilities, time ranges, durations
       - Manual assignments (specific persons, locations)
       - All "conditions" fields from template
    
    2. optimised (JSON): Optimisation OUTPUTS (read-only from optimiser)
       - Assigned start/end times
       - Assigned location(s)
       - Assigned person(s)
       - Generated by optimiser - never manually edited
    
    3. final (JSON): Admin-adjusted OUTPUTS (manual edits)
       - Copied from optimised when admin makes changes
       - Represents the actual schedule to be used
       - Falls back to optimised if empty
    
    4. additional (JSON): Non-optimisation metadata
       - Notes, reference data, budget codes
       - All "arbitrary" fields from template
       - Never touched by optimiser
    
    Example structure:
    {
      "constraints": {
        "required_capabilities": ["leadership", "technical"],
        "time_range": {"start": "10:00", "end": "14:00"},
        "duration": 90,
        "manually_assigned_persons": [15]
      },
      "optimised": {
        "start_time": "10:30",
        "end_time": "12:00",
        "assigned_persons": [15, 23],
        "location": 5
      },
      "final": {
        "start_time": "10:45",
        "end_time": "12:15",
        "assigned_persons": [15, 23, 42],
        "location": 5
      },
      "additional": {
        "notes": "Important meeting",
        "budget_code": "ABC123"
      }
    }
    """
    __tablename__ = "tasks"
    
    id = Column(Integer, primary_key=True, index=True)
    event_id = Column(Integer, ForeignKey("events.id"), nullable=False)
    task_template_id = Column(Integer, ForeignKey("task_templates.id"))
    task_type_id = Column(Integer, ForeignKey("task_types.id"), nullable=False)
    title = Column(String, nullable=False)
    description = Column(Text)
    
    # Four-field design: clear separation of concerns
    constraints = Column(JSON, default=dict)  # Optimisation inputs
    optimised = Column(JSON, default=dict)    # Optimisation outputs (direct from optimiser)
    final = Column(JSON, default=dict)        # Admin-adjusted outputs (manual changes)
    additional = Column(JSON, default=dict)   # Non-optimisation metadata
    
    # Task classification flags (copied from template on creation)
    is_floating = Column(Boolean, default=False, nullable=False)  # Floating vs Static
    is_transfer = Column(Boolean, default=False, nullable=False)  # Transfer vs Normal
    
    created_at = Column(DateTime(timezone=True), server_default=func.now())
    updated_at = Column(DateTime(timezone=True), onupdate=func.now())
